### ISSUE TITLE
Trim Section is not defined dynamically

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#76]
The trim section is defined in a static way. It must be done dynamically depending on the binning and ROI.

**Comment by simontorres** [comment]
In fact is so static that completely forgot Imaging. Solving this today.

**Comment by simontorres** [comment]
Fixed this, for imaging it takes `TRIMSEC` from header.
Some testing is needed.

**Comment by simontorres** [comment]
What happens to custom ROI?
 - Should we included a table of trim section values?

**Comment by cbaorion** [comment]
Let's is not worry about custom ROIs.  If somebody wants to use the pipeline for that, let them modify it themselves.  The documentation within the pipeline should allow users that want to go that way, to modify it to suit their very specific needs. Otherwise you will spend the rest of your life trying to make everybody coming with any possible custom ROI happy.  That is not the goal of the pipeline.

**Comment by simontorres** [comment]
Then, rather than finding the values ourselves we should be adding built-in flexibility for instance with #102

**Comment by simontorres** [comment]
There are no current issues with TRIM sections
