### ISSUE TITLE
Add a SNR limit on target detection.

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#99]
At the moment n-brightest targets are returned targets too faint should be discarded.

**Comment by cbaorion** [comment]
This is ok because at present we can only guarantee that the trace process will work on spectra with good SNR. For lower SNR spectra there is still a solution, which is to use the trace from a brighter object and just apply it directly to the faint targets, with just a recentering on the position of the faint spectrum as determined form the detection routine, that we know works even for very faint objects.

**Comment by simontorres** [comment]
This was actually a bug fixed on #266
